### ISSUE TITLE
Why null backend is not initialized with AUTO?

### ISSUE THREAD

**Issue by sammalt** [jarikomppa/soloud#216]
I am wondering why null backend is used only when explicitly asked for, and not with AUTO?

I don't think it's a big deal, but something a user of the library needs to understand and take into account - unless you deal with it, your application using SoLoud is not going to work with systems without audio devices.

**Comment by jarikomppa** [comment]
It's because the NULL backend isn't something you want unless you
explicitly want it.

**Comment by sammalt** [comment]
Ok, cool. So the approach for applications where audio is not mandatory, like games, you need to do either:
1. call init with AUTO. If it fails with NOT_IMPLEMENTED, call again with NULLDRIVER)
2. or leave SoLoud unitialized if AUTO fails, create a wrapper for SoLoud that checks for this and ignore all soloud calls in the wrapper layer if it has not been initialized.

**Comment by jarikomppa** [comment]
This is quite honestly an use case I have not considered (and for my
defense, neither has Spotify - just try to run it on a device with no audio
devices..)

The null driver wasn't designed for the purpose you describe, but I guess
it could be used for it. A lot of things will still break; audio streams do
not tick, time doesn't advance, etc, so any code that depends on those
would not work.

It would be easy to create a backend that does all the work, just throwing
away the samples, though. That would be closer to what you want (albeit it
would still be a waste of processing power, but it would work as expected)..

**Comment by Unit158** [comment]
A backend that can be piped to a file or something might be in order. It would be useful to stream the PCM data to a file (for DAWs, etc)


-------- Original message --------

**Comment by sammalt** [comment]
> This is quite honestly an use case I have not considered (and for my defense, neither has Spotify - just try to run it on a device with no audio devices..) 

Well Jari, neither had we, until we received a bug report about it. Quite understandable - it is an *audio* library after all.

Btw. apparently Spotify *has* considered it, since it seems to start on Windows without local audio devices if you have Spotify Connect set up. I was actually surprised to see that working.

**Comment by sammalt** [comment]
>The null driver wasn't designed for the purpose you describe, but I guess it could be used for it. A lot of things will still break; audio streams do not tick, time doesn't advance, etc, so any code that depends on those would not work. It would be easy to create a backend that does all the work, just throwing away the samples, though. That would be closer to what you want (albeit it would still be a waste of processing power, but it would work as expected)..

This left me a bit perplexed. What do you mean by this? What is the purpose of null driver then? Why does it exist? From the backend documentation (http://sol.gfxile.net/soloud/backends.html)

> Can be used to use SoLoud without audio device.

**Comment by jarikomppa** [comment]
They must have fixed spotify since I had problems with it then..

The null driver doesn't spin up a thread at all. To get audio data out of
SoLoud, you need to call the mix function directly from the application.
Some people have also found uses for it, apparently it's useful in
integrating with RetroArch.

There's also a demo of using the null driver in the SoLoud distribution
which "plays" a speech sample and draws the waveform in ascii. The same
kind of thing could be used to save wave files, if someone wanted a
speech-to-wav converter, for example.

I'll try to find time to roll up a "real" no-sound backend. I am, however,
a bit torn whether such should be automatically picked in case other audio
devices fail, as silent failure (gosh I wish that was an intended pun) is
probably not what developers want in this case.

**Comment by jarikomppa** [comment]
Now that the no-sound driver exists, I think we can close this.
