### ISSUE TITLE
How to use the File interface from C?

### ISSUE THREAD

**Issue by jarroddavis68** [jarikomppa/soloud#331]
I'm looking to use soloud with PhysFS (loading from a zip archive). How do I create a File interface from the C interface?

**Comment by Green-Sky** [comment]
I did this some time ago.
It's not very readable, because is goes through a PhysFS wrapper, but should still map to the underlying PhysFS calls.
https://github.com/MadeOfJelly/MushMachine/blob/master/framework/sound/src/mm/soloud_filesystem_file_impl.hpp
https://github.com/MadeOfJelly/MushMachine/blob/master/framework/sound/src/mm/soloud_filesystem_file_impl.cpp

Also, I think I did not test this well...

**Comment by jarroddavis6889** [comment]
Hi, oh sweet. Thx for the code. I'm using soloud from Delphi so I am forced to use the C interface. Unless I just totally missed it, I'm not seeing any way to access the File interface from C. I just see where File is defined as a pointer, but no other C routines that allow all you to create a File structure and be able to use it from C. I'm using the soloud_20200207 prebuilt distro.

**Comment by Green-Sky** [comment]
Oh boi, Delphi...
I see 3 options for you:
- loose the Delphi :P (ignore me lol)
- write the file implementation in cpp and load it separately (idk if this is worth your trouble)
- load the (whole) file to memory and load the sound from that memory

The last option should be the easiest to do, but might result in more memory usage than you need.
