### ISSUE TITLE
3D positional audio interface concerns

### ISSUE THREAD

**Issue by neilogd** [jarikomppa/soloud#99]
It seems to me like it would be much better as a layer on top on AudioSource, it's not obvious which of the calls for setting up properties such as volume or pitch will be incompatible. I propose that the code which handles the 3D audio parameters is moved out of AudioSource, and into a layer above. This will help remove some ambiguity, as well as make the core of SoLoud cleaner.

If the 3D API sits on top of AudioSource, there could also be a blanket "Anything you call that changes parameters of the audio is invalid" rule, and no problems at all. It also means those who don't want 3D audio don't end up seeing any of the interface too.

I'm finding it a little difficult to work with at the moment as its hard to make any assumptions about how it would work.

**Comment by neilogd** [comment]
Perhaps would it be better to have an AudioSource3d which implements the extra functionality which derives from AudioSource, and implements the extra bits required?

**Comment by jarikomppa** [comment]
Currently the 3d audio is built on top of the 2d audio; if it's in use, it simply overrides any manual volume/panning/play speed settings. Since it's becoming obvious that people want to adjust such things manually as well as have the 3d audio, I'll have to add separate 3d audio values and mix them at some point.

**Comment by jarikomppa** [comment]
Separate stuff added.
